variables: 
  ## Add this under variables section in the pipeline
  azureSubscription: Azure for Students
  appName: dotnotnoob
  containerRegistry: dotnetnoob

## Add the below snippet at the end of your pipeline
- task: AzureWebAppContainer@1
  displayName: 'Azure Web App on Container Deploy'
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(appName)
    containers: $(containerRegistry)/$(imageRepository):$(tag)