trigger:
- main

variables:
  # Container registry service connection established during pipeline creation
  imageRepository: dotnetapp
  containerRegistry: dotnetnoob
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: dotnettest
    appName: dotnotnoob
    containers: $(containerRegistry)/$(imageRepository):$(tag)